server:
  port: 8081

spring:
  security:
    user:
      name: mao
      password: $2a$12$V9qG.mWReqUAZrRJk2OEEuE3MKBCNY46YS0xXPduPMMeUuncI8dDu
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios_bd
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"